name: video_trimmer_2
description: A Flutter plugin to trim videos on Android and iOS.
version: 0.1.0
homepage: https://github.com/mokshchadha/video_trimmer_2

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mokshchadha.video_trimmer_2
        pluginClass: VideoTrimmer2Plugin
      ios:
        pluginClass: VideoTrimmer2Plugin